import {PropsWithChildren} from "react";
import {Pressable,StyleSheet,Text,View} from "react-native";
import {Ionicons} from "@expo/vector-icons";
import {colors,radius} from "./theme";
export function ScreenHeader({eyebrow,title,action}:{eyebrow?:string;title:string;action?:string}){return <View style={s.header}><View>{eyebrow&&<Text style={s.eyebrow}>{eyebrow}</Text>}<Text style={s.title}>{title}</Text></View>{action&&<Pressable style={s.iconBtn}><Ionicons name={action as any} size={22} color={colors.ink}/></Pressable>}</View>}
export function Card({children,style}:{children:React.ReactNode;style?:any}){return <View style={[s.card,style]}>{children}</View>}
export function Pill({children,tone="green"}:PropsWithChildren<{tone?:"green"|"neutral"|"amber"}>){return <View style={[s.pill,tone==="neutral"&&s.pillNeutral,tone==="amber"&&s.pillAmber]}><Text style={s.pillText}>{children}</Text></View>}
export function Progress({value}:{value:number}){return <View style={s.track}><View style={[s.fill,{width:`${Math.min(1,value)*100}%`}]}/></View>}
const s=StyleSheet.create({header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:24},eyebrow:{fontSize:13,color:colors.muted,fontWeight:"700",letterSpacing:.7,textTransform:"uppercase",marginBottom:5},title:{fontSize:32,lineHeight:38,fontWeight:"800",letterSpacing:-1.1,color:colors.ink},iconBtn:{width:44,height:44,borderRadius:22,backgroundColor:colors.card,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:colors.line},card:{backgroundColor:colors.card,borderRadius:radius.lg,padding:20,borderWidth:1,borderColor:colors.line},pill:{alignSelf:"flex-start",backgroundColor:colors.greenSoft,borderRadius:radius.pill,paddingHorizontal:10,paddingVertical:6},pillNeutral:{backgroundColor:colors.surface},pillAmber:{backgroundColor:"#F4E8D7"},pillText:{fontSize:12,fontWeight:"700",color:colors.ink},track:{height:7,borderRadius:99,backgroundColor:"#EAE8E0",overflow:"hidden"},fill:{height:"100%",borderRadius:99,backgroundColor:colors.green}});
